### ISSUE TITLE
Importing scene from compendium leads to empty canvas

### ISSUE THREAD

**Issue by Serban-AndreiC-2054619** [dev7355608/perfect-vision#292] opened 2022-09-29 20:14 UTC
### Expected Behavior

I'm simply trying to import scenes from a compendium of mine. Tested it with new scenes and new compendiums, the errors seem to be there all the same.

### Current Behavior

After the scenes are imported, when I move to them the canvas is empty and 2 errors appear in the console. If I click to another scene and back to the faulty, imported one, then the errors are gone and the scene is visible properly.

Weirdly enough, if I drag the scene from the compendium to the scene bar these errors don't show up. It's only when I explicitly use the "Import Entry" button.

### Steps to Reproduce

1. Create a compendium.
2. Create a scene.
3. Put said scene in compendium.
4. Import said scene from compendium using the "Import Entry" button.
5. View the imported scene.

### Context

![Screenshot_1](https://user-images.githubusercontent.com/71814850/193131797-ece2e006-ddb7-4cb3-b58d-a493ffedf8cf.png)
![Screenshot_2](https://user-images.githubusercontent.com/71814850/193131811-30ab1b4c-c1be-4873-86d5-075b600aefd1.png)

### Version

v4.0.21

### Foundry VTT Version

v10.286

### Operating System

Windows 10

### Browser / App

Native App (Electron)

### Game System

dnd5e (v2.0.3)

### Relevant Modules

x

**Comment by dev7355608** [comment] 2022-09-30 16:44
I'm unable to reproduce it. I created a new compendium and a new default scene in a new world, placed it in the compendium and imported it. No errors on switch.

The error tells me that something must have gone wrong earlier. Are there any other error messages or warnings in the console?

No other modules (except libWrapper) are enabled, correct?

If you import scenes from the compendium with all modules deactivated, you get no errors?

**Comment by Serban-AndreiC-2054619** [comment] 2022-09-30 21:05
The only modules active are Perfect Vision and libWrapper, yes. With no modules active importing scenes works as expected. There are no other warning or error messages in the console.

After further testing I discovered one more thing : when you import the scene via the 'Import Entry' button, the 'Configure Scene' window shows up. What I usually do is click it away with the 'Close' button in the top right corner since there's nothing I need to change anyway, but if instead I just click on 'Save Changes' then the scene works as intended. Maybe the issue lies there somewhere?

**Comment by dev7355608** [comment] 2022-10-02 17:31
> After further testing I discovered one more thing : when you import the scene via the 'Import Entry' button, the 'Configure Scene' window shows up. What I usually do is click it away with the 'Close' button in the top right corner since there's nothing I need to change anyway, but if instead I just click on 'Save Changes' then the scene works as intended. Maybe the issue lies there somewhere?

That was it. It's a bug in Foundry. I reported it and expect it to be fixed in Stable 4.

**Closed by dev7355608** 2022-10-02 17:31 UTC
