### ISSUE TITLE
Compatibility issue with FX master in Foundry V9

### ISSUE THREAD

**Issue by zacdemon** [dev7355608/perfect-vision#166] opened 2021-12-24 15:44 UTC
Uncertain if this is on your end or theirs so I'll be opening a similar ticket on their github, but when both of these modules are enabled, new scenes will fail to load.

https://github.com/ghost-fvtt/fxmaster

**Comment by dev7355608** [comment] 2021-12-24 23:32
Duplicate of #167. Fixed in 3.2.3.

**Closed by dev7355608** 2021-12-24 23:32 UTC
