### ISSUE TITLE
Problem with Better Target - Severe Impact

### ISSUE THREAD

**Issue by Nedrapter** [dev7355608/perfect-vision#145] opened 2021-10-31 05:41 UTC
When having Perfect Vision and Better Target modules and trying to target a small sized token by double right clicking on it, the user's interface freezes and becomes unresponding.
The following errors pop in the console:
![image](https://user-images.githubusercontent.com/74311190/139569620-588a3ea7-bded-4f46-b9ef-ada2960506d0.png)
I know the Better Target is not mentioned in those error, but the problem only happens when those 2 modules are active and target a small token.

**Comment by Nedrapter** [comment] 2021-10-31 05:42
System: dnd 5e

**Comment by dev7355608** [comment] 2021-10-31 11:29
Thanks for the report, but I'm unable to reproduce it. Double right-click doesn't target a token by default, but opens the token config. And by small token do you mean any token with width and height equal to 0.5? Did you check whether this bug happens if PV, Better Target and libWrapper are the only active modules?

**Comment by dev7355608** [comment] 2021-10-31 11:34
Never mind, seems like it was fixed in the latest Better Target release.

**Closed by dev7355608** 2021-10-31 11:34 UTC
