### ISSUE TITLE
Full map becomes revealed to players if they switch to a different scene and back again (firefox only)

### ISSUE THREAD

**Issue by cs96and** [dev7355608/perfect-vision#42] opened 2021-01-06 11:34 UTC
- Foundry 0.7.9
- Perfect Vision 1.5.0

If a player is on a map with fog of war, and they switch to another publicly accessible scene and back again, then the whole map is revealed to them.  This only happens in Firefox, and when Perfect Vision is enabled.  E.g.

Initial player view...
![image](https://user-images.githubusercontent.com/898086/103763844-558efe00-5012-11eb-830a-2266c44cbd35.png)

View after switching to a different scene and back again...
![image](https://user-images.githubusercontent.com/898086/103763909-6b042800-5012-11eb-87f8-ec14d277154e.png)

Also, here's the really weird thing.  If you log in with Firefox after a fog reset then the problem happens.  But if I reset the fog, then log in as a player with Vivaldi (chromium based), then the problem does not occur.  However if I then log back in as the same player with Firefox, then the problem no longer occurs in Firefox either.  Somehow the initial Vivaldi log in prevents the problem happening in Firefox.

**Comment by dev7355608** [comment] 2021-01-06 12:54
That's super weird. I wasn't able to reproduce it unfortunately. Do you get any errors in the console? Could you try to send me a simple world with two scenes and one token that has this problem?

**Comment by cs96and** [comment] 2021-01-06 22:13
This only seems to happen in Firefox on Linux.  On Windows, I ran into a slightly different issue (a strange portion of the map is revealed) that happens regardless of whether Perfect Vision is enabled or not.

I've attached a world with two scenes and a single actor.  You can log in as GM or "Bob" (no password for either) and flick between the two scenes to trigger the issue.

Linux: Debian 10 (with backported 5.9 kernel)
Firefox: 84.0.2

[perfect-vision-test.tar.gz](https://github.com/dev7355608/perfect-vision/files/5778430/perfect-vision-test.tar.gz)

**Comment by dev7355608** [comment] 2021-01-06 23:30
Thanks. I'll try to reproduce it in a VM. And could you send me a screenshot that shows the strange portion of the map that is revealed without Perfect Vision?

**Comment by cs96and** [comment] 2021-01-06 23:38
I submitted a bug report to core Foundry for the other problem
https://gitlab.com/foundrynet/foundryvtt/-/issues/4442

**Comment by cs96and** [comment] 2021-01-07 01:26
BTW, if you use a Debian VM, I am using the the latest version of firefox downloaded from the mozilla website, not the one from apt.

Also, I have a hunch this may be hw acceleration related, so not sure if it will reproduce in the VM or not, and you may have to force firefox to enable hw acceleration.

**Comment by corpocracy** [comment] 2021-03-01 04:35
Hate to pile on, but I also had this issue in my game today. No one else was having a problem (including someone using Firefox). But one of my players who was on a Mac and using Firefox did have this issue. It was really weird. I would reset the fog of war, then he would walk around the room and at certain points in the room, the fog of war for the whole map would disappear. I would reset, he would walk around, and then he could see everything again. He refreshed, he logged out, I stopped my Forge server, he tried Firefox on a different computer, but it still kept happening. It wasn't until he logged into the game under Chrome on a different computer that he stopped having issues. I couldn't talk him through finding the console log and I haven't been able to reproduce on my end. I do have a short video though of him sharing his screen that clearly shows the issue.

https://user-images.githubusercontent.com/62632755/109452361-948f6d80-7a1d-11eb-85d3-44752fb0b4c9.mp4

**Comment by dev7355608** [comment] 2021-03-20 20:04
@corpocracy I doubt this is Perfect Vision's fault. I feel like this is a different issue than the one above. Foundry's sight system has some bugs (see [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/3909)) which will be fixed in Foundry 0.8.2 hopefully. Those kind of problems are very hard to track down, especially without a way to reproduce it. Sorry that I can't be of more help at the moment.

**Comment by neovatar** [comment] 2021-04-07 21:59
I have a very similar issue, also Firefox and Linux. Moving a Token around in a player session might reveal the whole fog of war area as "explored" (visible, but masked). Seems kind of non deterministic, but it happens after a few moves, even if you just move forth and back the same squares a few times. If I disable the perfect vision, everything works as expected.

**Comment by neovatar** [comment] 2021-04-08 10:46
After a few more tests: With perfect vision active the whole FOW is marked as explored, without Perfect Vision the FOW is only lifted on rooms with light sources.

I also tend to blame a Foundry FOW bug - when using Perfect Vison this bug seems to be triggered on a larger scale since in manipulates lightning. Basically Foundry seems to reveal FOW of sealed off parts of the map when they have a light source.

**Comment by dev7355608** [comment] 2021-04-08 17:02
@neovatar Interesting observation. Could you send me a simple scene that has this problem? I'd like to try to reproduce it.

**Comment by neovatar** [comment] 2021-04-08 17:16
@dev7355608 Just the json? Or is there a way to export the scene with the background image?

**Comment by dev7355608** [comment] 2021-04-08 17:20
@neovatar Just the json. I don't need the assets.

**Comment by neovatar** [comment] 2021-04-08 17:24
[fvtt-Scene-FOW-Test.zip](https://github.com/dev7355608/perfect-vision/files/6280373/fvtt-Scene-FOW-Test.zip)

https://user-images.githubusercontent.com/550533/114070228-133ebc80-98a0-11eb-9d94-4333b4f2b761.mp4

**Comment by neovatar** [comment] 2021-04-08 17:35
Scene:
[fvtt-Scene-FOW-Test.zip](https://github.com/dev7355608/perfect-vision/files/6280423/fvtt-Scene-FOW-Test.zip)

**Comment by neovatar** [comment] 2021-04-08 17:54
Video of the bug:
[foundry-fow-bug.zip](https://github.com/dev7355608/perfect-vision/files/6280551/foundry-fow-bug.zip)

**Comment by neovatar** [comment] 2021-04-08 17:56
I added a video of the bug - I was only able to reproduce it on "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0", did not happen with Firefox in WIndows 10.

**Comment by neovatar** [comment] 2021-04-08 18:50
Yes, I also did another try with all Firefox add-ons disabled, just to be sure, but had same results.

I just opened a bug in the Foundry tracker: https://gitlab.com/foundrynet/foundryvtt/-/issues/4850

**Comment by neovatar** [comment] 2021-04-08 18:56
And that is how the bug looks with Perfect Vision active:

![grafik](https://user-images.githubusercontent.com/550533/114081427-d4fbca00-98ac-11eb-8708-bf117e61671c.png)

**Comment by dev7355608** [comment] 2021-04-11 17:21
PV 1.8.0 includes a hack to fix the FoW issue; at least the problem reported by @neovatar (let me know if it works).

And I would like to know if this has any impact on the issues described by @cs96and and @corpocracy. If you could let me know, whether it makes any difference, that would be great. And let me please know what color is shown when you run [this test](https://www.pixiplayground.com/#/edit/NufJle1TvQQR8Jrj9_r_O) in the OS and browser that you experienced the problem with.

**Comment by neovatar** [comment] 2021-04-11 17:59
@dev7355608 just did a quick test with PV 1.8.0 and FoundryVTT 0.7.9 (without my monkey patch). I can confirm, that the workaround you included in PV fixes the issue.

**Comment by cs96and** [comment] 2021-04-12 10:16
I can confirm that 1.8.0 fixes the bug I reported.  I re-tried it with 1.7.3 and the bug was still present.  Upgrading to 1.8.0 fixed the issue.

**Comment by dev7355608** [comment] 2021-04-12 10:39
@cs96and Good to know. Just to make sure: if you run [this test](https://www.pixiplayground.com/#/edit/NufJle1TvQQR8Jrj9_r_O), I assume it shows yellow, right?

**Comment by cs96and** [comment] 2021-04-12 10:46
I get green

**Comment by dev7355608** [comment] 2021-04-12 10:54
In Firefox? That's odd: if you get green, the hack to fix it shouldn't be enabled. Do you get a notification in Foundry that says "Rendering bug detected. [...]"?

**Comment by cs96and** [comment] 2021-04-12 10:54
Yep I got a notification saying the hack was enabled.  yet I get green in that test.

**Comment by cs96and** [comment] 2021-04-12 10:55
That's firefox in Linux BTW.

**Comment by dev7355608** [comment] 2021-04-12 11:07
Does [this test](https://www.pixiplayground.com/#/edit/f6a5xynE4jY9izZGxn7f7) show a tiny triangular face or a complete bunny?

**Comment by cs96and** [comment] 2021-04-12 11:13
Tiny triangular face

**Comment by dev7355608** [comment] 2021-04-12 11:26
Have you only ever had problems when switching scenes, or did you also experience that the whole map is revealed when you move tokens like the others described?

**Comment by cs96and** [comment] 2021-04-12 11:31
I've only noticed it when switching back and forth between scenes.

**Closed** 2021-07-31 02:50 UTC
