### ISSUE TITLE
Token Lighting is being put off center and is showing it emit in a square

### ISSUE THREAD

**Issue by Avitale34** [dev7355608/perfect-vision#65] opened 2021-04-14 05:06 UTC
If I assign lighting to a token it puts it off to the right and down instead of on the token and it emits in a square
![image](https://user-images.githubusercontent.com/65961637/114657212-96577c80-9cbd-11eb-9dd8-484941cae91f.png)

**Comment by bjornsundell** [comment] 2021-04-14 06:43
I have this problem too. In Foundry 0.7.9. Disabled all other modules,placing a light source offsets the "effect" part of the lightsource.

**Comment by dev7355608** [comment] 2021-04-14 10:01
I'm unable to reproduce this. Please create a new simple test scene that shows the problem and share it with me.

Also what OS and browser are you using? Does it happen in a different browser or PC as well?

**Comment by bjornsundell** [comment] 2021-04-14 14:29
Running on a iMac2019 macOS BigSur 11.2.3 Chrome  Version 89.0.4389.128 (Officiell version) (x86_64)

https://user-images.githubusercontent.com/82496804/114726336-972ff300-9d3d-11eb-8826-cb0931a44a32.mov

**Comment by bjornsundell** [comment] 2021-04-14 14:42
Same thing running it in crome. Seems to me (and I'm a layman) that the color emission is ofset and comes from the corver of the square instead of coming from the center.

![PerfectVision](https://user-images.githubusercontent.com/82496804/114729549-600f1100-9d40-11eb-92a2-1b74aebd3c57.jpg)

**Comment by dev7355608** [comment] 2021-04-14 15:17
PV 1.8.0 is the only active module? And this doesn't happen with PV 1.7.3?

**Comment by bjornsundell** [comment] 2021-04-14 15:43
It's the only active module. It did not happen in 1.7.3. How do I downgrade? I can try it out again

**Comment by thenomain** [comment] 2021-04-14 23:46
Drawn to this because of the same problem, Foundry 0.7.9, PV 1.8.0 (only active module), macOS 10.15.7, Firefox 87.0. Same issue, different offset. Here's my map with Perfect Vision (and no other modules):
![image](https://user-images.githubusercontent.com/935160/114794036-a6249e80-9d59-11eb-819e-8459b884fd1c.png)

And without any modules (walls shown):
![image](https://user-images.githubusercontent.com/935160/114794093-bfc5e600-9d59-11eb-87bf-65e1f333379f.png)

Didn't happen before I updated all of my modules. Will test on Windows tonight.

Thanks.

**Comment by dev7355608** [comment] 2021-04-14 23:55
I figured out what the problem is: it's a bug in pixijs. It only affects retina display basically. I'll release a fix shortly.

**Comment by dev7355608** [comment] 2021-04-15 01:06
Fixed in v1.8.3.

**Closed by dev7355608** 2021-04-15 01:06 UTC

**Comment by bjornsundell** [comment] 2021-04-15 06:14
Sorry - but enabling PerfectVision now ends up with the message:
Canvas drawing failed for the LightingLayer, see console for more details.
I get a blank screen, turning Perfect Vision 1.8.1 off makes the canvas load correctly. How do I access the console so I can give you the information there?

**Comment by dev7355608** [comment] 2021-04-15 12:13
Fixed in v1.8.2. (#66)
