### ISSUE TITLE
Global Illumination Setting no longer available

### ISSUE THREAD

**Issue by ca3du5** [dev7355608/perfect-vision#78] opened 2021-06-07 18:39 UTC
Just recently updated Foundry to 0.8.6. The Global Illumination setting is nowhere to be found in my scene configuration. Just an FYI. This was how I allowed humans to see in Daylight conditions. If anyone has recommendations, will also take those too. Thanks.

**Comment by dev7355608** [comment] 2021-06-08 00:13
I need to improve the description in the readme. Duplicate of #76.

**Closed by dev7355608** 2021-06-08 00:13 UTC
