### ISSUE TITLE
Newest update seems to be causing error "Canvas drawing failed for the token layer, see the console for more details"

### ISSUE THREAD

**Issue by zkkng** [dev7355608/perfect-vision#90] opened 2021-07-31 03:40 UTC
Immediately stops when I disable perfect vision and resumes when I enable it.

**Current module list**
```
about-time--v1.0.4;
advanced-macros--v1.9;
animation-preview--v1.0.2;
autocomplete-whisper--v0.3.3;
autoanimations--v0.5.07;
background-volume--v1.3.0;
betterrolls5e--v1.5.6;
betterroofs--v0.9.8.2;
beyond20--v1.3;
burger-time--v0.1.9;
caeora-maps-tokens-assets--v1.0.4;
chat-drop--v1.0.0;
chat-images--v2.5.3;
chat-portrait--v0.4.6;
CommunityLighting--v0.4.7;
ddb-importer--v2.2.1;
deprecated-modules--v1.1.4;
df-manual-rolls--v2.2.1;
dfreds-convenient-effects--v1.6.3;
dfreds-droppables--v1.2.7;
dice-so-nice--v4.0.7;
dice-calculator--v1.2.1;
DragTransfer--v1.2.1;
drag-ruler--v1.7.7;
dragupload--v2.0.0;
dramatic-rolls--v1.5.0;
Dynamic-Effects-SRD--v5.0.01;
dae--v0.8.35;
easy-exports--v0.6.1;
floating-combat-toolbox--v1.2.1;
forien-quest-log--v0.7.5;
forien-unidentified-items--v0.2.5;
foundry_community_macros--v0.44.0;
foundryvtt-arms-reach--v1.2.4;
free-loot-tavern-compendium--v1.9.1;
fvtt-encounter-stats--v0.14.1;
fxmaster--v1.2.1;
giffyglyphs-5e-monster-maker--v1.0.0;
gm-notes--v0.4.1;
gm-screen--v2.8.1;
gm-secrets--v1.0.0;
hey-wait--v0.6.1;
hide-gm-rolls--v0.10.1;
vtta-iconizer--v2.1.15;
illandril-inventory-sorter--v1.1.2;
illandril-token-hud-scale--v1.4.1;
item-delete-check--v1.1.3;
animated-spell-effects--v0.6.8;
jb2a_patreon--v0.1.9;
jitsirtc--v0.6.1;
lessfog--v0.8.5;
lmrtfy--v1.17;
lib-captions--v0.1.2;
colorsettings--v2.5.9;
lib-df-hotkeys--v2.3.4;
lib-wrapper--v1.8.0.0;
lichtgeschwindigkeit--v1.4.1;
LockView--v1.4.12;
lootsheetnpc5e--v3.1.0;
magicitems--v2.1.1;
monks-active-tiles--v1.0.18;
multilevel-tokens--v1.5.2;
navbar-tweaks--v1.0.5.0;
notokenanim--v3.1;
NotYourTurn--v1.1.5;
parallaxia--v0.3.6;
perfect-vision--v2.0.0;
pin-cushion--v1.5.0;
pings--v1.2.12+0.8.6;
polyglot--v1.7.6.3;
popout--v2.1;
rc-spent-ammo--v1.0.13;
sequencer--v0.5.9;
settings-extender--v1.1.6+0.8.6;
foundryvtt-simple-calendar--vv1.3.8;
simplefog--v0.1.18;
skill-customization-5e--v2.3.0;
smalltime--v1.10.2;
socketlib--v1.0.8;
SoundBoard--v1.5.2;
SoundBoard-BlitzFreePack--v1.0.0;
SoundBoard-BlitzCommunityPack--v1.0.0;
soundfxlibrary--v1.0.1;
spell-level-buttons-for-dnd5e--v1.02;
mad-caverns--v1.2;
mad-forestwild--v1.1;
mad-mythicgreece--v1.2;
mad-urbanext--v1.5;
mad-wizardschoice--v1.1;
tidy-ui_game-settings--v0.1.23;
t-is-for-target--v0.4;
toggle-combat-warning--v0.1.7;
token-attacher--v4.1.2;
vtta-tokenizer--v3.4.5;
tokenmagic--v0.5.2.1;
turnmarker--v2.8.1;
dd-import--v2.1.0;
zoom-pan-options--v1.6.5;
```

**Errors I believe are relevant from the console**

```precision mediump float;
#define SHADER_NAME pixi-shader-56
precision mediump float;
  uniform float alpha;
  uniform float ratio;
  uniform vec3 colorDim;
  uniform vec3 colorBright;
  varying vec2 vUvs;
  
 $1void main0(float alpha, float ratio) $1void main0(float alpha, float ratio) {
      float dist = distance(vUvs, vec2(0.5)) * 2.0;
      vec3 color = mix(colorDim, colorBright, step(dist, ratio));
      gl_FragColor = vec4(color * alpha, 1.0);
  }

// Patched by Perfect Vision

                varying vec2 pv_MaskCoord;

                uniform bool pv_IsSight;
                uniform bool pv_IsDarkness;
                uniform sampler2D pv_Illumination;

                void main()
                {
                    float a = alpha;
                    float r = ratio;

                    if (pv_IsSight) {
                        float s = texture2D(pv_Illumination, pv_MaskCoord).r;
                        a *= mix(1.0, 0.8125, s);
                        r *= (1.0 - step(1.0, s));
                    } else if (!pv_IsDarkness) {
                        float s = texture2D(pv_Illumination, pv_MaskCoord).b;
                        r = max(r, s);
                    }

                    main0(a, r);
                }
```

```
ERROR: 0:10: '$' : invalid character
ERROR: 0:10: '1void' : invalid number
ERROR: 0:10: 'main0' : syntax error
````

```
core.min.js:8 Pixi.js Error: Could not initialize shader.
```

```
gl.VALIDATE_STATUS false
````

```
gl.getError() 0
```

```
TypeError: Failed to execute 'getProgramParameter' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at e.getAttributeData (core.min.js:8)
    at e.extractData (core.min.js:8)
    at new e (core.min.js:8)
    at Function.e.from (core.min.js:8)
    at Function.create (foundry.js:46622)
    at PointSource.🎁PointSource.prototype._createContainer#perfect-vision (lighting.js:347)
    at PointSource.wrapper (patch.js:66)
    at x.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:549)
    at PointSource.🎁PointSource.prototype._createContainer#0 (libWrapper-wrapper.js:162)
    at new PointSource (foundry.js:36938)
    at new Token (foundry.js:44247)
    at new Token5e (token.js:26)
    at TokenLayer.createObject (foundry.js:19510)
    at TokenDocument5e.get object [as object] (foundry.js:8369)
    at foundry.js:19494
    at Map.map (collection.mjs:145)
    at TokenLayer.draw (foundry.js:19493)
    at async Canvas.draw (foundry.js:17503)
    at async Scene.view (foundry.js:15481)
```

**Comment by dev7355608** [comment] 2021-07-31 04:11
Thanks for the report. That's odd. I can't really explain it. Try v2.0.1.

**Comment by dev7355608** [comment] 2021-08-02 19:01
I assume it was fixed.

**Comment by Shuggaloaf** [comment] 2021-08-21 23:31
Hi there, I am also having this problem. I see the author abandoned the topic but I'm not sure if this can be re-opened or if I need to submit a new issue? Using version 2.8.0

Verified the issue is caused by this mod by simply toggling on and off and also double checking by using Find the Culprit.  

If there is anything specific you want me to submit, I'm happy to do so. Or if you want me to start a new issue I can do that as well.

**Comment by dev7355608** [comment] 2021-08-21 23:39
Latest version is 2.8.11. Do you get the same error in the console? What OS/browser are you using?

**Comment by Shuggaloaf** [comment] 2021-08-21 23:47
> Latest version is 2.8.11

Odd I just downloaded this mod about an hour ago through the FVTT app and it gave me 2.8.0. Any idea why that is? 

> Do you get the same error in the console?
Doesn't look like it. Not showing anything that specifically says "perfect vision" but this is the only error I'm getting so I guess it must be this one?
![image](https://user-images.githubusercontent.com/79543184/130337526-aa5f9346-30de-4340-8698-b19ea2bf467a.png)

> OS/browser?
Win 10 64, Chrome and native app both having issue.

**Comment by dev7355608** [comment] 2021-08-21 23:57
This error should be fixed with the latest version (it isn't the bug in this issue). Let me know if that's the case. I think it downloaded 2.8.0, because I was to lazy to update the version in the foundry database. But it should update to the latest version if you click update. I actually didn't now that it doesn't check for updates after installing it. I'll keep the foundry database up to date from now on.

**Closed by dev7355608** 2021-08-21 23:57 UTC

**Comment by Shuggaloaf** [comment] 2021-08-22 00:04
Updating fixed both issues. No worries on being lazy. I am known to be this way myself sometimes. ;-) 
Thanks for the fix (and the great mod!), you can re-close this one.
