### ISSUE TITLE
Issue with Thumbnail Regneration

### ISSUE THREAD

**Issue by fuzzlewump** [dev7355608/perfect-vision#150] opened 2021-11-24 18:30 UTC
Hi,

On a new 0.8.9 foundry world, dnd 5e, only libwrapper and perfect vision enabled. After creating a a couple new blank scenes, adding something to their backgrounds, then clicking regenerate thumbnail image, something strange happens: the tile it is attempting to grab for the thumbnail appears on the canvas as a temporary overlay of sorts instead of the scene thumbnail area. And, the thumbnail is not regenerated. It seems to only happen when a 'blank' scene is made, i.e., a scene created without a background image already.

Thanks,
![desktop1](https://user-images.githubusercontent.com/72497607/143294863-83c2fb63-4a97-4022-8300-e802e7287e92.gif)

**Comment by dev7355608** [comment] 2021-11-24 18:34
Duplicate of #149.

**Closed by dev7355608** 2021-11-24 18:34 UTC
