### ISSUE TITLE
Conflict with Levels.

### ISSUE THREAD

**Issue by rinnocenti** [dev7355608/perfect-vision#99] opened 2021-08-01 07:36 UTC
in 2.0 holes was working, but in the latest versions it doesn't. tokens not rendering in holes.

**Comment by zstombaugh** [comment] 2021-08-01 08:05
I think I might be experiencing this issue, too. Seems limited to token vision, as it is able to be bypassed via GM Vision toggle.

Here's an example where it occurs without any Levels set. 
https://gyazo.com/fb61d905ad713cc89b5bf3c1f51543d9

This is how it should appear.
https://gyazo.com/2024c1bb1fabe665810877a7ef6969a7

Foundry 0.8.8. I have verified that it works as intended if Levels OR Perfect Vision are disabled.

**Comment by dev7355608** [comment] 2021-08-01 10:00
Let me know if v2.2.1 is working correctly.

**Comment by rinnocenti** [comment] 2021-08-01 17:33
almost
he is not respecting the level of the hole. it displays the tokens in the hole and above the character's level (even without a hole)
![image](https://user-images.githubusercontent.com/3178127/127780128-d4fe7577-e770-4672-bd8e-749c3421cba6.png)
perfect vision, show tokens above. Out of the hole, upstairs.

![image](https://user-images.githubusercontent.com/3178127/127780103-1cbf2d30-8df9-4b4c-86b7-cef034552d91.png)
without perfect vision (expected behavior)

**Comment by zstombaugh** [comment] 2021-08-01 17:47
> 
> 
> Let me know if v2.2.1 is working correctly.

Closer to the expected behavior! Other tokens now seem to disappear on-hover. Again, this is without any levels set. This effect is relative to differences in elevation, meaning zeroes will see zeroes and tens will see tens but hovering over a ten while selecting a zero will make the token disappear.
https://gyazo.com/3a0c04eb1cb10ef5c7edb978488ace03

No errors showing in the console still. Adjusting settings of Levels or Perfect Vision with both modules active had no effect.

**Comment by dev7355608** [comment] 2021-08-01 18:07
Thanks for feedback. PV substitutes a lot of Levels token/tile manipulation. No errors are to be expected. I have very little real Levels knowledge, so I someone can send me a little test scene it would help, I think.

**Comment by dev7355608** [comment] 2021-08-02 18:59
I think it fixed it. Check out v2.3.0, and let me know.

**Comment by zstombaugh** [comment] 2021-08-02 19:33
> 
> 
> I think it fixed it. Check out v2.3.0, and let me know.

Working as expected on my end,. Thank you!

**Comment by rinnocenti** [comment] 2021-08-02 20:04
Not here.
without a real level, works.
but whit a level. the roof ends up not being displayed.
Tokens are displayed correctly, but tiles are not.
I'm going to create a simple 3 level map for testing.
![image](https://user-images.githubusercontent.com/3178127/127916845-07363e64-8391-4aa4-8894-67dfb2163ba5.png)
perfect vision active, the tile of level is not showing. (the toknes is showing correctly)
![image](https://user-images.githubusercontent.com/3178127/127917120-1174ef32-08d1-4cfc-9c96-b23d485d9276.png)
without perfect vision (expected behavior)

**Comment by rinnocenti** [comment] 2021-08-02 20:09
[Scene.zip](https://github.com/dev7355608/perfect-vision/files/6919353/Scene.zip)

**Comment by dev7355608** [comment] 2021-08-02 21:18
Shipped a bug in v2.3.0. Fixed it in v2.3.1. Let me now if that was it.

**Comment by rinnocenti** [comment] 2021-08-03 01:06
I make a video (my first time ever whenever I speak english, sorry for that )

https://youtu.be/eUsdtf7mE7I

**Comment by zstombaugh** [comment] 2021-08-03 08:28
> 
> 
> I make a video (my first time ever whenever I speak english, sorry for that )
> 
> https://youtu.be/eUsdtf7mE7I

I had no problems following your English. :) Based on your video, I think I was able to replicate the unexpected token behavior with v2.3.1 installed. It uses a single set of stairs with 4 levels (no holes). I am still learning Levels, so it is like that I made a mistake in the setup somewhere, but seems the bug for token visibility _across levels_ remains.

Without token selected:
https://gyazo.com/ab705fa20ebdbbbcdef299324600dd4e

With token selected:
https://gyazo.com/76bca05e1df9e94ace4ea6ac226066ba

Also replicated that it can vary based on the assigned level, such that the ground level selection may see all three other tokens and portraits (in my example) but the fourth level selection would only HP bars and elevation markers on other tokens.

**Comment by rinnocenti** [comment] 2021-08-03 15:14
improved a lot.
however some problems occur one happens whenever tiles are within the levels.
another doesn't always happen, it could be a race condition.

[video.zip](https://github.com/dev7355608/perfect-vision/files/6925173/video.zip)

**Comment by dev7355608** [comment] 2021-08-03 21:40
Try v2.3.4.

**Comment by Morrinn** [comment] 2021-08-03 22:20
Some issues have been stabilized, but tokens on different elevated levels still are not showing up properly.

**Comment by rinnocenti** [comment] 2021-08-03 23:09
Most bugs have actually been stabilized.
but as the guy Morrinn, tokens in some cases are still showing up tokens in diferents levels still showing up. again seems to be race conditions.

**Comment by dev7355608** [comment] 2021-08-04 06:41
Did you test with the most recent Levels versions? theripper made some changes that affect PV: I'll need to go trough the changes and adjust PV.

**Comment by rinnocenti** [comment] 2021-08-04 06:53
Yes I test with recent Levels. and and the error happens much less often.
sometimes tokens are not rendered when changing levels. but when it selects an other token and returns it, it "updates" and corrects.
but tokens being rendered at the wrong level, it hasn't happened anymore

**Comment by rinnocenti** [comment] 2021-08-04 06:56
token on root level, not showing.
![image](https://user-images.githubusercontent.com/3178127/128135654-5ea65288-16c6-45ea-8fe4-edd7d629c2df.png)

**Comment by dev7355608** [comment] 2021-08-04 11:31
theripper changed how he hides tokens in the most recent release. I adjusted for that in v2.3.5. Let me know if you run into more issues.

**Comment by dev7355608** [comment] 2021-08-05 15:13
More fixes in the newest PV release (2.5.1). Let me know if you notice any issues.

**Comment by Tarbarian** [comment] 2021-08-05 15:38
I'm not sure if this would be the better place or a new issue involving overhead tiles, but currently icons and bars are showing through overhead tiles with just Perfect Vision installed on a PF1e world, see images below.
With Perfect Vision: 
![image](https://user-images.githubusercontent.com/76751079/128378949-c4af7ee9-9fa1-4a82-a1fe-9214f57df064.png)
Without Perfect Vision: 
![image](https://user-images.githubusercontent.com/76751079/128378608-2bafc637-ea7e-4261-b6d7-cf4b48697e16.png)

This is with 2.5.1, Foundry 0.8.8, and Pathfinder 1 0.78.15.

**Comment by rinnocenti** [comment] 2021-08-05 15:58
Here is the same in DND5e

**Comment by dev7355608** [comment] 2021-08-05 17:45
This issue should be it's own. But I learned today that HP bars and status effects will be over foreground tiles in Foundry v9 as of right now (prototype 1): same as it is with PV right now. So I'm likely not going to change anything about it at the moment or in the future if it's going to be the default behavior.

**Comment by dev7355608** [comment] 2021-08-05 18:56
Follow up: Since there are no walls, the token (from the token's point of view) would actually see the other token under the overhead tile, while you, looking down, cannot see it. So technically the token under the overhead tile isn't actually invisible. If you think about it this way, it actually makes sense that you see at least the HP bars etc.

**Comment by dev7355608** [comment] 2021-08-06 10:43
I'm closing this. If you experience more Levels-related issues, please open a new issue. If you want to discuss the other issue further, please open a separate issue.

**Closed by dev7355608** 2021-08-06 10:43 UTC
