### ISSUE TITLE
v9: Tokens with dim vision cannot see in dim light in when a scene has a sight limit set

### ISSUE THREAD

**Issue by strongpauly** [dev7355608/perfect-vision#153] opened 2021-12-06 19:12 UTC
After upgrade, tokens which have a dim vision radius can only see themselves in dim light.  Moving/creating a nearby light source enables their vision.

Using Dungeons & Dragons 5e vision rules and foundry build V9 233.

**Comment by dev7355608** [comment] 2021-12-06 21:29
I'm unable to reproduce this. Do you get errors messages (F12 -> Console)?

**Comment by strongpauly** [comment] 2021-12-07 18:50
I have a sight limit set on the scene to 60.  Turning this off (setting it to empty) re-enables vision for tokens with dim vision

Also checked for errors in console, only a warning stating:
`foundry.js:4940 game.data.version is deprecated since V9 in favor of game.version`.
This was with only perfect vision and libWrapper enabled.

**Comment by dev7355608** [comment] 2021-12-07 20:11
Thanks! Fixed in v3.0.2.

**Closed by dev7355608** 2021-12-07 20:11 UTC

**Comment by strongpauly** [comment] 2021-12-07 21:08
Tested and looks good!
