### ISSUE TITLE
Perfect Vision causing foundry to often hang during reloads in chromium based browsers

### ISSUE THREAD

**Issue by OmegaRogue** [dev7355608/perfect-vision#324] opened 2023-02-09 21:09 UTC
### Expected Behavior

Foundry loads in a reasonable amount of time

### Current Behavior

Foundry doesnt load when reloading

### Steps to Reproduce

1. Enable perfect vision
2. open a world
3. reload the tab
4. if it loads in a reasonable amount of time, keep refreshing, after a few refreshes at most it stops loading

### Context

There are no errors, this only happens on chrome and chromium based browsers (including the foundry app), in firefox it doesnt happen.
To find this module (and a few others, tokenizer and active-effect-manager-lib, independently from this, when at least one of those modules was enabled in addition to my other modules, it stops loading) i opened a new tab in chrome, opened the dev tools, and started a performance profiler recording, then put in the url to my foundry instance (on localhost) in, waited for a minute, stopped the recording, killed the tab process in the chrome task manager, and then refreshed the tab to load the report results. In the report results, it looks like these modules were causing infinite loops in the network category.
I followed this guide here for finding javascript infinite loops to find it https://abduvik.medium.com/how-to-find-infinite-loops-in-javascript-using-devtools-ea5fc84aec73

Active Modules:
----------
About Time v;
Active-Auras v;
Active Token Effects v;
Advanced Drawing Tools v;
Advanced Macros v;
Ammo Tracker v;
Argon - Combat HUD v;
Automated Animations v;
Automated Evocations - Companion Manager v;
Auto-Rotate v;
Baileywiki Cabal Dungeon v;
Baileywiki Landing Pages v;
Baileywiki Maps Premium v;
Baileywiki Maps Towns v;
Baileywiki Nuts and Bolts v;
Better Roofs v;
Boss Bar v;
Combat Booster: Turn Marker, Recent Actions and more v;
Combat Carousel v;
Combat Utility Belt v;
Compendium Folders v;
Custom CSS v;
Custom Fonts v;
Day Night Cycle v;
DF Architect v;
DF Chat Enhancements v;
DF Curvy Walls v;
DF Flags Editor v;
DF Quality of Life v;
DFreds Convenient Effects v;
DFreds Droppables v;
DFreds Effects Panel v;
DFreds Pocket Change v;
DF Scene Enhancement v;
Dice So Nice! v;
Dice Tray v;
Dig Down - Advanced Search v;
DnD5e Drag Ruler Integration v;
Drag Ruler v;
Drag Upload (Get Over Here!) v;
Dungeon Draw v;
Dynamic effects using Active Effects v;
Elevated Vision v;
Enhanced Terrain Layer v;
Epic Rolls 5e v;
Filepicker + v;
Find the culprit v;
FlexUI v;
Forgotten Adventures Battlemaps v;
Foundry Achievements v;
Foundry Community Macros v;
FXMaster v;
Gatherer v;
Health Estimate v;
Hover Distance v;
Image Context v;
Item Containers v;
Item Delete Check v;
Item Macro v;
Item Piles v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Let Me Roll That For You! v;
Levels v;
Levels - Automatic Cover Calculator v;
Levels - Depth Blur v;
Levels - Volumetric Templates v;
lib - Color Settings v;
Library: Chat Commands v.0.0;
Library: DF Module Buttons v;
Library: Scene Packer v;
libWrapper v.0;
Link Item and Resource DnD5e v;
Lock View v;
Loot Sheet NPC 5e (Simple Version) v;
Lost Mines by dransky v;
Magic Items v;
Mastercrafted - Crafting Manager v;
Midi QOL v;
Midi SRD v;
Module Compatibility Checker v;
Monk's Active Tile Triggers v;
Monk's Little Details v;
Monk's Player Settings v;
Monk's Scene Navigation v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
More Automated Spells Items and Feats v;
Moulinette Core v;
Multiattack 5e v;
Multiface Tiles v;
Multilevel Tokens v;
Nap Time (5E) v;
Not Your Turn! v;
Party Overview v;
Pin Fixer v;
Pings v;
Polyglot v;
Quick Encounters v;
Roll Groups v;
Sequencer v;
Settings Extender v;
Sidebar and Windows Resizer v;
Simple Calendar v;
Smart Target v;
socketlib v;
Splatter v;
Stealthy v;
Tabletop RPG Music v;
Tagger v;
Terrain Ruler v;
TheRipper93's Module Hub v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Tile Scroll v;
Tile Sort v;
Times Up v;
Token Action HUD Core v;
Token Action HUD D&D 5e v;
Token Attacher v;
Token Lean: Peek Around Corners v;
Token Magic FX v;
Token Mold v;
Token Variant Art v;
Token Z v;
Torch v;
uchideshi34's Dragon of Icespire Peak Maps v;
uchideshi34's Lost Mine of Phandelver Maps v;
Walled Templates v;
Wall Height v;
Warp Gate v;

### Version

v4.1.16

### Foundry VTT Version

v10.291

### Operating System

Arch Linux, Windows 10, Windows 11

### Browser / App

Native App (Electron), Chrome, Edge, Other

### Game System

dnd5e (2.1.4)

### Relevant Modules

active-effect-manager-lib (0.1.24), tokenizer (3.10.1)

**Comment by dev7355608** [comment] 2023-06-08 02:20
I've never experienced this issue myself, never seen anyone else mention it, and haven't been able been able to reproduce it. It must be a very weird module interaction if it is indeed caused by PV. Very hard to tell what the problem is. I'll close this issue, because I can't repro it.

**Closed by dev7355608** 2023-06-08 02:20 UTC
Labels: bug, nonrepro
