### ISSUE TITLE
Normal vision token can see other tokens in darkness

### ISSUE THREAD

**Issue by JesterOC** [dev7355608/perfect-vision#226] opened 2022-03-05 17:00 UTC
Foundry version 9 build 254
Pathfinder 2e version: 3.6.0.10666
Versions: Perfect vision 3.7.3

Normal sighted token can see in darkness

Player view in darkness
![image](https://user-images.githubusercontent.com/954708/156892760-460147ed-3fd9-45dc-b7de-89d04eb24338.png)

GM view no light sources and token vision settings
![image](https://user-images.githubusercontent.com/954708/156892836-2ca2c814-6418-4c5d-848b-32f1b1d41706.png)

**Comment by dev7355608** [comment] 2022-03-05 17:16
Please show me your scene settings.

**Comment by JesterOC** [comment] 2022-03-05 18:22
Scene settings

![image](https://user-images.githubusercontent.com/954708/156895573-606e15ba-3520-484a-b39f-a1b67f9b2489.png)

**Comment by JesterOC** [comment] 2022-03-05 18:26
Interesting. If I pull up the scene settings and save them. It starts working. Then if I drag and move the token, it breaks again

Before
![image](https://user-images.githubusercontent.com/954708/156895639-69dac11e-0a5e-4cc0-b2ef-ac99b8ac0747.png)

Config screen up
![image](https://user-images.githubusercontent.com/954708/156895656-f47243c5-8b9a-487b-b064-93533f54b8f5.png)

Save config screen
![image](https://user-images.githubusercontent.com/954708/156895667-a574d4b7-25fa-408b-b052-9bc269cd29a0.png)

Move token
![image](https://user-images.githubusercontent.com/954708/156895676-bd3afb38-7f67-4a18-b54a-0263f55b1a7b.png)

**Comment by dev7355608** [comment] 2022-03-05 18:36
The token should be able to see because the Darkness Level is 0 and therefore Unrestricted Vision Range is enabled because of the Vision Limitation Threshold.

But saving the scene settings shouldn't change it like you describe. I'll look into that.

**Comment by JesterOC** [comment] 2022-03-05 18:53
Got it. Thank you, should we close this?

**Comment by dev7355608** [comment] 2022-03-05 21:37
The issue caused by closing the scene config has been fixed.

**Closed by dev7355608** 2022-03-05 21:37 UTC
