### ISSUE TITLE
New Senses Format Compatibility with PF1e 

### ISSUE THREAD

**Issue by Tarbarian** [dev7355608/perfect-vision#258] opened 2022-05-28 23:45 UTC
PF1e has implemented a new sense system where the senses are set in the sheet rather than in the prototype token. This causes incompatibility issues with Perfect Vision. 
The relevant commit can be found here: [commit](https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/commit/4d340be088f5b3b3f74edfa63a723c950e162f37)
The data structure can be found in the template: [template](https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/commit/4d340be088f5b3b3f74edfa63a723c950e162f37#8499fe8fb818346158860026ab2cf8dc4c614eab)

**Comment by dev7355608** [comment] 2022-05-29 00:04
What kind of issues? If you have error messages, please share them with me.

**Comment by Tarbarian** [comment] 2022-05-29 00:22
Unfortunately I can't seem to replicate it. It may have been from migrating tokens with established Perfect Vision token configs to the new system. It was causing a failure to render the lighting layer that resolved when I removed Perfect Vision, but I cannot provide an error until I can replicate the issue. I will continue investigating to see if I can locate the conflict more precising.

**Comment by dev7355608** [comment] 2022-05-29 00:45
I think there is a migration issue in the system. I got a report two weeks ago, but the error must have been caused by PF1e writing undefined/NaN in dimSight/brightSight if I recall correctly. I then pushed a fix in order to prevent it from breaking if PF1e messed this up. Make sure you have the latest PV version installed.

**Comment by davidoford** [comment] 2022-06-13 16:45
Having issues with Pf1 as well
The token's 'bright vision' box was greyed out with pf1's new sense system. To add bright 60, you have to go into the character sheet's attribute tab, and under senses put in 'Darkvision 60'. This give you vision in the dark again,
But then it doesn't utilize perfect vision's monochrome darkvision look.

**Comment by dev7355608** [comment] 2022-06-28 16:45
I assume there's no longer an issue. Should that not be the case, let me know.

**Closed by dev7355608** 2022-06-28 16:45 UTC
