### ISSUE TITLE
When creating a new tile, the tile border is left on screen, even after moving the tile.

### ISSUE THREAD

**Issue by MorganVergara** [dev7355608/perfect-vision#214] opened 2022-02-13 16:01 UTC
See the video.

https://user-images.githubusercontent.com/30846057/153761498-7fd9f7f6-9f57-4b91-88bd-c9056e6a4972.mp4

I've used FindTheCulprit to narrow it down to Perfect Vision, and disabled all modules other than perfect vision to confirm. 

Environment:
Foundry VTT 9.249
DnD5e System 1.5.7
PerfectVision 3.6.13

Please let me know if you need other information.

Thanks!

**Comment by MorganVergara** [comment] 2022-02-13 16:02
Oh, refreshing eliminates the left-over border, so it appears to be temporary. Also, it's not interactive; can't click on it or move it, so it appears to be just a graphics glitch.

**Comment by dev7355608** [comment] 2022-02-13 17:28
Thanks for the report! Turns out it's actually caused by a core Foundry bug (I reported it). I included a fix for this issue in the latest PV release.

**Closed by dev7355608** 2022-02-13 17:28 UTC

**Comment by MorganVergara** [comment] 2022-02-13 19:44
You know, I kinda figured it had to be something in core. Made no sense
that PV should be affecting tile placement like that. Thanks for letting me
know and for the fix.
