### ISSUE TITLE
FR: option fordarkness inside lighting drawings as offset instead of absolute

### ISSUE THREAD

**Issue by esheyw** [dev7355608/perfect-vision#320] opened 2022-12-12 05:37 UTC
### Description

I think it'd be neat if we could have an area that was always X value (or Y%) darker than the scene base (or parent lighting area, but that's probably not possible). 

### Context

I don't have any specific use cases in mind yet, this just seems like something someone could do interesting things with if offered.

**Comment by dev7355608** [comment] 2023-06-08 02:33
More or less a duplicate of #227.

Perfect Vision is discontinued (see #334).

**Closed by dev7355608** 2023-06-08 02:33 UTC
Labels: enhancement
