### ISSUE TITLE
Shape Lighting Tools no longer respect vision rules (PF2E)

### ISSUE THREAD

**Issue by tuhs1985** [dev7355608/perfect-vision#174] opened 2022-01-01 22:19 UTC
Running it on v9 (Build 238) in a PF2e world (v.3.1.3.9639) rules-based vision-enabled:  When I try to use its lighting tool tab for shapes, it no longer respects the vision rules.  i.e. if I set the shape to darkness value of 1, darkvision does not work.  However if I set the scene darkness to value 1, darkvision works as expected.  This also happens if i override and shut off unrestricted vision range in the shape

https://discord.com/channels/170995199584108546/722566083499786352/926496040696315984

**Comment by dev7355608** [comment] 2022-01-02 02:30
I currently working on that. It's not that simple to fix. I have to override some of the PF2e code and add my own code to make rules-based vision work as intended with lighting areas. I'll have to do some testing to make sure it works right. But it should be ready for release in the next 24 hours.

**Comment by CmdSoda** [comment] 2022-01-02 11:15
You are doing great work. Thank you so much.

**Comment by tuhs1985** [comment] 2022-01-02 18:01
Yup, agreed, great work.  Didn't know if you preferred tracking in here or not - which is why I reposted.  Wasn't trying to be pushy!

**Comment by dev7355608** [comment] 2022-01-02 19:29
No worries.

Fixed in 3.3.0.

**Closed by dev7355608** 2022-01-02 19:29 UTC
