### ISSUE TITLE
TypeError: Cannot read property 'filters' of null

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [dev7355608/perfect-vision#33] opened 2020-12-22 18:27 UTC
This happens right after my world has loaded in FoundryVTT, starting on the activated scene (a landing page with no lights).

Possibly a conflict between the Perfect Vision and Dynamic Illumination modules.

````
foundry.js:2499 TypeError: Cannot read property 'filters' of null
    at Function._updateMonoFilter (perfect-vision.js:964)
    at Function._updateScene (perfect-vision.js:317)
    at perfect-vision.js:1549
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at foundry.js:29630
    at Array.map (<anonymous>)
    at Function._handleUpdate (foundry.js:29622)
    at Function.update (foundry.js:29603)

````
FoundryVTT version: 0.7.9
Perfect-vision: 1.2.16
Dynamic Illumination: 0.7.7

**Comment by dev7355608** [comment] 2020-12-22 21:46
Duplicate of  #30. This was fixed in v1.2.18.

**Closed by dev7355608** 2020-12-22 21:46 UTC
